ALTER TABLE episodes ADD COLUMN score INTEGER;
ALTER TABLE episodes ADD COLUMN time INTEGER;
ALTER TABLE episodes ADD COLUMN coins INTEGER;
ALTER TABLE episodes ADD COLUMN life INTEGER;
ALTER TABLE episodes ADD COLUMN status TEXT;
ALTER TABLE episodes ADD COLUMN y_pos INTEGER;
ALTER TABLE episodes ADD COLUMN world INTEGER;
ALTER TABLE episodes ADD COLUMN stage INTEGER;
